creating a load screen
ampp8800/Hochu_pomoch pull request #1
Opened 2021-12-19 12:08 UTC by ampp8800

2021-12-19 14:02 UTC, EitherNor commented
![image](https://user-images.githubusercontent.com/19414663/146677599-cd4667a6-be35-4538-ade3-7db3a555351e.png)
![image](https://user-images.githubusercontent.com/19414663/146677603-50806af0-4f69-4a38-a454-4c2dbb0b5cac.png)

1. Расстояние от прелоадера до текста "загрузка" сильно больше, чем в дизайне
2. Горизонтальная ориентация - см второй скрин, без комментариев

2021-12-19 14:08 UTC, EitherNor commented
У тебя куча мусора залетело, все файлы .webp сноси - это картинки в другом формате, файлы самого градла типа gradlew тоже

2021-12-19 14:10 UTC, EitherNor requested changes

2021-12-19 14:10 UTC, EitherNor commented on app/src/main/res/layout/main.xml
> +    android:orientation="vertical">
По-моему этот атрибут не нужен

2021-12-19 14:10 UTC, EitherNor commented on app/src/main/res/layout/main.xml
> +        app:layout_constraintHorizontal_bias="0.498"
Этот параметр отвечает за процентное расположение на экране, у тебя больше подойдут обычные привязки краёв

2021-12-19 14:10 UTC, EitherNor commented on app/src/main/res/layout/main.xml
> +        android:text="Загрузка..."
Все строки должны храниться в файлах strings.xml, здесь должны быть ссылки на строковые ресурсы

2021-12-19 14:10 UTC, EitherNor commented on app/src/main/res/layout/main.xml
> +        android:id="@+id/textView"
Названия вьюх всегда делай как названия переменных - понятные, что это и зачем. TextView начинай с tv, например tvGachiTextView, картинку с iv... и тд.

2021-12-19 14:10 UTC, EitherNor commented on app/src/main/res/layout/main.xml
> +        android:id="@+id/progressBar"
То же самое с названием элемента, должно быть понятно с какого он экрана как минимум

2021-12-19 14:10 UTC, EitherNor commented on app/src/main/res/layout/main.xml
> +        android:id="@+id/textView"
Касается всех айдишников вьюх и прочих компонентов

2021-12-19 14:10 UTC, EitherNor commented on app/src/main/AndroidManifest.xml
> +    package="ru.startandroid.develop.trysecond">
пакет чужой

2021-12-19 14:10 UTC, EitherNor commented on app/proguard-rules.pro
> +# Add project specific ProGuard rules here.
Файл пустой по сути, он вообще нужен?

2021-12-19 14:10 UTC, EitherNor commented on app/src/main/java/ru/startandroid/develop/trysecond/MainActivity.java
> +package ru.startandroid.develop.trysecond;
Перенеси приложение на свой пакет

2021-12-23 19:22 UTC, ampp8800 commented on app/src/main/res/layout/main.xml
> +    android:orientation="vertical">
![16249873766550](https://user-images.githubusercontent.com/87927435/147283789-7724a7d4-b583-4579-bbc6-8c8775af80d7.png)
вот так я понимаю

2021-12-23 19:23 UTC, ampp8800 commented on app/src/main/res/layout/main.xml
> +        app:layout_constraintHorizontal_bias="0.498"
горизонталь тут не нужна, видимо зараковал, почистил

2021-12-24 07:49 UTC, EitherNor commented
gradlew, gradlew.bat - эти файлы тоже надо убрать, это исполняемые файлы гредла (сборщика проектов), которые не нужно тащить в гит

2022-03-26 14:17 UTC, closed without merging