Event details
ampp8800/Hochu_pomoch pull request #10
Opened 2022-08-29 15:08 UTC by ampp8800

2022-08-29 16:00 UTC, EitherNor commented
Общие замечания:

- Кнопка назад в тулбаре не работает. Системная кнопка выкидывает из приложения. Они обе должны возвращать на список новостей
- Кнопка "напишите нам" должна предлагать создать новое письмо, а не отправлять на гугл ком
- Плейсхолдеры картинок не надо показывать - ты же не знаешь, сколько их будет, 1 или 3. По умолчанию картинки должны быть скрыты и показывать их надо только после понимания, что картинка есть
- Список друзей не должен быть прибит гвоздями к низу экрана, он должен скроллиться вместе со всем контентом вертикально

2022-08-29 16:00 UTC, EitherNor requested changes

2022-08-29 16:00 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/api/NewsItem.java
> +public class NewsItem {
У тебя есть уже вроде класс с таким именем.  Так как это сетевая модель, добавь Model в конец

2022-08-29 16:00 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/api/NewsItem.java
> +    private List<Long> convertStringToArrayLongs(@NonNull String string) {
@NN

2022-08-29 16:00 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/api/NewsItem.java
> +    private List<String> convertStringToArrayStrings(@NonNull String string) {
@NN

2022-08-29 16:00 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/DatabaseNewsRepository.java
> +                news.add(new NewsItem(newsEntity.getGuid(),
Вместо того, что дрочить поля в каждом месте конвертации - унеси это внутрь NewsItem, сделай там конструктор, принимающий NewsEntity

2022-08-29 16:00 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NetworkNewsRepository.java
>                      newsEntityDao.insert(newsItemToNewsEntity(item.getGuid(),
то же самое, метод newsItemToNewsEntity внезапно должен принимать на вход NewsItem, о чем и говорится в его названии

2022-08-29 16:00 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EvevntDetailFragment.java
> +public class EvevntDetailFragment extends Fragment {
Опечатка в названии класса

2022-08-29 16:00 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EvevntDetailFragment.java
> +    private final String NEWS_ITEM_GUID = "newsItemGuid";
ARG_...

2022-08-29 16:00 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EvevntDetailFragment.java
> +            NetworkNewsRepository.newInstance().loadNews(new NewsLoadingCallback() {
Коллбек одинаковые на обе ветки ифа. Вынеси его в переменную перед if

2022-08-29 16:00 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EvevntDetailFragment.java
> +    private ArrayAdapter<String> getPhoneNumbers(@NonNull List<Long> phoneNumbersOnLong) {
Чето по названию метода вообще не ожидаю получить какой-то ArrayAdapter

2022-08-29 16:00 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EvevntDetailFragment.java
> +        if (friends.size() > 5) {
5 по крайней мере можно в константы вынести с понятным названием

2022-08-29 16:00 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EvevntDetailFragment.java
> +    private void loadingDataForCurrentFragment(@NonNull List<NewsItem> list, @NonNull String guid) {
Ты же задавал вопрос и я сказал, что логику поиска надо унести в репозиторий. Ты из него должен получать уже только один айтем

2022-08-29 16:00 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +    private boolean isConnected(@NonNull Context context) {
У тебя этот код повторяется несколько раз. Сделай NetworkStateHelper и у него через статический метод спрашивай состояние подключения

2022-08-29 16:00 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +        evevntDetailFragment.setGuid(guid);
Сразу в newInstance передавай аргумент и там сеть

2022-08-29 16:04 UTC, EitherNor requested changes

2022-08-29 16:04 UTC, EitherNor commented on app/src/main/res/layout/fragment_event_detail.xml
> +    <de.hdodenhof.circleimageview.CircleImageView
Если у тебя здесь ровно то же самое, что в профиле - выноси в отдельный лейаут и инклудь в двух местах, зачем столько копипасты-то

2022-09-05 19:21 UTC, epereskokov requested changes

2022-09-05 19:21 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/api/NewsItem.java
> +    public String getDate() {
этот класс - дто, просто объект для передачи информации. А этот метод содержит ui-логику, как формировать дату для отображения. UI-логика должна находиться в UI-слое, то есть во фрагменте или активити. Вот туда надо это логику и перенести (и логику из convertStringToArrayLongs тоже).

2022-09-05 19:21 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EvevntDetailFragment.java
> +    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, @Nullable Bundle saveInstanceState) {
при нажатии "назад" меня должно возвращать на список новостей, а не на главный экран, нужно доработать.

2022-09-05 19:21 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EvevntDetailFragment.java
> +        ((TextView) view.findViewById(R.id.tv_news_name)).setText(newsItem.getName());
обычно вью - это переменные класса, значения в которые присваиваются в onViewCreated или в onCreateView, во-первых это удобнее читать, а во-вторых зачастую вью используется в нескольких методах в классе.

2022-09-05 19:21 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EvevntDetailFragment.java
> +                view.findViewById(R.id.iv_cardimage).setVisibility(View.GONE);
switch без break - это плохо. Скрой по-умолчанию в xml-разметке все 3 вьюхи и показывай их и добавляй в них изображение, проходя for-ом по images. А целевые ImageView сохрани в список в onCreateView или в onViewCreated.

2022-09-05 19:21 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EvevntDetailFragment.java
> +            case 5:
тут я бы сделал примерно ту же логику. Ты конечно хитро придумал, молодец, но так свитч (без break  в каждой ветке) лучше не использовать, это трудночитаемый источник ошибок.

2022-09-11 15:46 UTC, EitherNor requested changes

2022-09-11 15:46 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/Converter.java
> +    public static List<String> convertStringToArrayStrings(@NonNull String string) {
в названии написано массив. по факту на выходе список. С другими методами то же самое

2022-09-11 15:46 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/Converter.java
> +public class Converter {
Надо добавить в название что-то, чтобы было понятно, что это конвертер формата данных

2022-09-11 15:46 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EevntDetailFragment.java
> +public class EevntDetailFragment extends Fragment {
Опечатка. И плюс у тебя детали, а не одна деталь

2022-09-11 15:46 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EevntDetailFragment.java
> +            public void onNewsItemUpdate(@NonNull NewsItemModel nim) {
называй параметры полностью

2022-09-11 15:46 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EevntDetailFragment.java
> +    private void setUpAppBar(ActionBar actionBar) {
нн

2022-09-11 15:46 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EevntDetailFragment.java
> +    private void setReceivedData() {
Тут нет гарантии, что при такой логике работы с newsItemModel он уже будет на момент вызова метода. Лучше передай его в этот метод параметром нон-нулловым

2022-09-11 15:46 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EevntDetailFragment.java
> +        for (int i = 1; i <= friends.size(); i++) {
Зачем здесь свитч вообще нужен? У тебя и так есть индекс, просто сеть и показывай элемент по индексу в цикле и все. С фотками то же самое

2022-09-11 15:46 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NetworkStateHelper.java
> +        ConnectivityManager cm = (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);
Это вынеси в переменную класса, зачем её создавать при каждой проверке?

2022-09-11 16:28 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/data/DatabaseNewsRepository.java
> +                if (newsEntity.getGuid().equals(guid)){
ты из базы вытягиваешь сразу все значения, а потом фильтруешь нужное? Зачем, если можно сразу сделать select в базе и вытащить только нужное?

2022-09-11 16:28 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/data/NetworkNewsRepository.java
> +            AppDatabase database = HochuPomochApplication.getInstance().getDatabase();
здесь тоже самое, должен быть метод в репозитории NewsEntity findNewsByGuid(String guid), который возвращает тебе уже нужно значение. Плюс код дублируется, создай отдельный класс одинаковой асинк таски и переиспользуй ее в обоих местах.

2022-09-11 16:28 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/Converter.java
> +            return "Осталось" + Days.daysBetween(currentDate, endDateTime) +
строкове константы хрантся в файле string.xml в ресурсах. Это делается для того, чтобы можно было удобно локализовывать строки для разных языков, просто раскладывая файлы с переводами в нужные папки в ресурсах - анжроид сам возьмет нужный файл в зависимости от текущей локализации. 
Ссылка на строку - это R.string.your_string_name, саму строку получаешь с помощью context.getResources().getString(R.string.your_string_name)

2022-09-11 16:28 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EevntDetailFragment.java
> +        requireActivity().findViewById(R.id.tv_toolbar_name).setVisibility(View.GONE);
4 раза повторяется вызов requireActivity().
Повторения кода - это плохо. Сохрани в переменную в методе активити и используй везде внутри метода.

2022-09-12 13:30 UTC, EitherNor approved these changes

2022-09-12 13:46 UTC, epereskokov requested changes

2022-09-12 13:46 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EventDetailsFragment.java
> +        EventDetailsFragment.guid = guid;
такие вещи передаются через бандл. После создания фрамгента в него можно положить бандл с нужной информацией, а к примеру в onCreate(или в любом другом методе жизненного цикла) фрагмента ты можешь этот параметр прочитать из бандла.

2022-09-12 13:46 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EventDetailsFragment.java
> +            if (i >= MAXIMUM_NUMBER_OF_IMAGES_TO_SHOW) {
MAXIMUM_NUMBER_OF_IMAGES_TO_SHOW дублирует размер idsImage, а значит эта константа - лишняя и нужно сразу ориентироваться на idsImage.length. Так же и со второй аналогичной константой ниже.

2022-09-13 10:30 UTC, epereskokov requested changes

2022-09-13 10:30 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EventDetailsFragment.java
> +        if (getArguments() != null) {
это лишнее, бандл, который передан при создании фрагмента и так будет сохранен при повороте экрана.

2022-09-13 10:30 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EventDetailsFragment.java
> +            guid = getArguments().getString(ARG_NEWS_ITEM_GUID);
здесь guid может и не быть, если разработчик (то есть ты) забыл его передать. Так что лучше проверять и падать с IllegalStateException, если guid не найден.

2022-09-13 10:30 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EventDetailsFragment.java
>          if (saveInstanceState != null) {
эта ветка if не нужна, guid всегда будет в аргументах, если его туда положили.

2022-09-13 12:29 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EventDetailsFragment.java
> +            throw new IllegalArgumentException();
В конструктор ошибки можно передать текст ошибки, который будет высвечиваться, это делается, чтобы сделать ошибку понятнее. Тут надо написать, что не передан необходимый идентификатор (по-буржуйски конечно писать, никакой латиницы)

2022-09-13 12:29 UTC, epereskokov approved these changes

2022-09-13 12:43 UTC, merged