Add moxy to the project
ampp8800/Hochu_pomoch pull request #11
Opened 2022-09-19 21:42 UTC by ampp8800

2022-09-20 08:13 UTC, EitherNor requested changes

2022-09-20 08:13 UTC, EitherNor commented on app/build.gradle
> +    def moxy_version = "1.0.13"
Последний релиз 2.2.2

2022-09-20 08:13 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsPresenter.java
> +                getViewState().setUpAppBar(newsItemModel);
Эти 2 команды всегда выполняются вместе - объедини в одну

2022-09-20 08:13 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsView.java
> +    void downloadLocationSelection(NewsItemLoadingCallback newsItemLoadingCallback);
Зачем во вью нужен какой-то коллбек? Ты должен репозитории вызывать из презентера, а во вью отдавать уже полученный результат

2022-09-20 08:13 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsView.java
> +    void setUpAppBar(NewsItemModel newsItemModel);
Везде, где надо - нон-нуллы или нуллаблы в параметрах команд

2022-09-20 08:13 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsView.java
> +public interface EventDetailsView extends MvpView {
Стратегии надо указывать в интерфейсе, а не в реализации

2022-09-20 08:13 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EventDetailsFragment.java
> +        requireActivity().findViewById(R.id.tv_toolbar_name).setVisibility(View.GONE);
активити так же в одну переменную можно вынести

2022-09-20 08:13 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsPresenter.java
> +    public void setPhotoFromNetwork(int idImageView, @NonNull String imageViewURL) {
В этом методе в презентере нет смысла - ты просто дергаешь из вью презентер и тут снова вызываешь вьюстейт. Сразу вызывай в активити нужный метод

2022-09-20 08:13 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EventDetailsFragment.java
> +        ((TextView) getView().findViewById(R.id.tv_fundName)).setText(newsItemModel.getFundName());
вью в переменнную, а лучше все поля вынести сразу на уровень класса и инициализируй в onCreateView

2022-09-20 13:07 UTC, EitherNor requested changes

2022-09-20 13:07 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsPresenter.java
> +    public void newsItemLoadingCallback(boolean isConnect, @NonNull String guid) {
isConnected - "подключено?"

2022-09-20 13:07 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsPresenter.java
> +    public void newsItemLoadingCallback(boolean isConnect, @NonNull String guid) {
Название метода надо поменять на просто "загрузить новости", это не получение коллбека же

2022-09-20 13:07 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsView.java
> +    @StateStrategyType(AddToEndStrategy.class)
Ты в реализации этого метода стартуешь новую активити. Её не нужно запускать повторно при повороте экрана - андроид сам поддерживает жизненный цикл активити и фрагментов. Соответственно стратегия будет другая

2022-09-20 13:07 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EventDetailsFragment.java
>      public void setPhotoFromNetwork(int idImageView, @NonNull String imageViewURL) {
Вроде метод может теперь быть приватным

2022-09-20 13:20 UTC, EitherNor requested changes

2022-09-20 13:20 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsView.java
> +    @StateStrategyType(SkipStrategy.class)
А если вью по какой-то причине была недоступна в момент выполнения команды? Нам действительно не актуально отработать нажатую пользователем кнопку?

2022-09-20 14:00 UTC, EitherNor approved these changes

2022-09-20 19:32 UTC, epereskokov requested changes

2022-09-20 19:32 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EventDetailsFragment.java
>          ((TextView) view.findViewById(R.id.tv_news_name)).setText(newsItemModel.getName());
все вьюхи обычно хранятся в переменных класса и инициализируются в методе onCreateView или onViewCreated. Это делается по той причине, что если вдруг лейаут изменился и там переименовались/пропали вьюхи, то ты бы сразу получил ошибку при открытии фрагмента, а не тогда, когда сработал нужный сценарий, в котором конкретная вьюха используется. Ведь сценарии могут быть очень замысловатыми.
Так что советую везде поступать именно так - давай начнем с этого класса, а потом как будешь что-то переделывать в других классах - то и там будешь менять этот момент.

2022-09-20 19:32 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/EventDetailsFragment.java
> +                getActivity().onBackPressed();
а тут происходит возврат на список новостей? Если да, то просто пропусти этот коммент, если нет - то доработай.

2022-09-20 19:32 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsPresenter.java
> +    public void loadNews(boolean isConnected, @NonNull String guid) {
по-хорошему фрагмент должен знать только о презентере, а вот уже презентер пускай знает о NetworkStateHelper и значение isConnected надо получать в презентере. Для работы этого метода нужен контекст. Ты можешь его получить так - в Application-классе в onCreate сохрани в статичную переменную ссылку на Application так: application = this, а потом тут в презентере дергай эту ссылку, у тебя будет applicationContext, которого достаточно для определения наличия интернета.

Сделано и сейчас правильно, эта доработка подготавливает кое-какие грядущие изменения.

2022-09-20 19:46 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsPresenter.java
> +    public void loadNews(boolean isConnected, @NonNull String guid) {
у тебя после каждого поворота экрана будет загружаться новость. Добавь флаг isInitialized  и после первого выполнения загрузки ставь его в true. Ну и проверяй перед загрузкой, если он в true, то значит все уже загружено.

2022-09-20 19:46 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsPresenter.java
> +        if (isConnected) {
у тебя нет обработки ошибок для загрузки из сети. Для эмуляции вставь Thread.sleep(10000) после этой проверки isConnected и отключи интернет в момент паузы, эмулируя к примеру сбой сети или ошибку сервера и посмотри, что случится. Сетевые ошибки - частое явление, надо быть к ним готовым.

2022-09-21 13:02 UTC, epereskokov requested changes

2022-09-21 13:02 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsPresenter.java
> +                Thread.sleep(3000);
это я предлагал сделать для теста, в итоговом коде лучше убрать.

2022-09-21 13:02 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsPresenter.java
> +                if (!NetworkStateHelper.isConnected(HochuPomochApplication.getInstance())) {
тебе это не поможет, я хотел, чтобы ты обрабатывал ошибку загрузки, она необязательно может случиться из-за отсутствия интернета. Например сбойнул севрер - у тебя вылетела ошибка и все сломалось. Тебе нужно тут перехватывать ошибку и пускать логику по альтернативному сценарию.

2022-09-21 13:02 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsPresenter.java
> +                    getViewState().showToast("no response from the network");
текста надо хранить в strngs.xml

2022-09-22 08:54 UTC, epereskokov approved these changes

2022-09-22 12:17 UTC, EitherNor requested changes

2022-09-22 12:17 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsPresenter.java
> +    private boolean isConnected;
зачем эта переменная на уровне класса?

2022-09-22 12:17 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsItemModelAndConnect.java
> +    boolean isConnected;
private final

2022-09-22 12:17 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsItemModelAndConnect.java
> +    private NewsItemModel newsItemModel;
final, Nullable

2022-09-22 12:17 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsItemModelAndConnect.java
> +    public NewsItemModelAndConnect(@NonNull NewsItemModel newsItemModel, boolean isConnected) {
Nullable же - если ошибка, то значения не будет

2022-09-22 12:17 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsItemModelAndConnect.java
> +    @NonNull
И здесь

2022-09-22 12:17 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/EventDetailsPresenter.java
> +            if (isConnected) {
Чето здесь не то. У тебя все эти проверки должны быть в коллбеке же, а сейчас этот код моментально выполнится и будет дефолтное false всегда

2022-09-22 12:24 UTC, EitherNor requested changes

2022-09-22 12:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NetworkNewsRepository.java
>              return null;
Почему здесь нулл? У тебя теперь этот метод должен всегда отдавать объект, меняется только его содержимое. И надо не проверять подключение к сети, а отлавливать сетевую ошибку же. Наличие подключения ты должен определять ДО вызова сетевой загрузки

2022-09-22 12:58 UTC, EitherNor approved these changes

2022-09-22 13:02 UTC, merged