Add moxy to news fragment
ampp8800/Hochu_pomoch pull request #13
Opened 2022-10-01 14:49 UTC by ampp8800

2022-10-04 20:05 UTC, EitherNor requested changes

2022-10-04 20:05 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
>          swipeRefreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
Листенер можно проставить и в onCreateView, зачем этот код в методе, который должен только показывать загруженные новости?

2022-10-04 20:05 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/NewsPresenter.java
> +        if (!isInitialized) {
А что мешает использовать onFirstViewAttach вместо этого костыля?

2022-10-04 20:05 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/NewsView.java
> +    void setUpAppBar();
Почему это должно быть командой вьюстейта? Какие данные нам нужны, чтобы переключить видимость 2 вьюх и установить статичный тайтл экрана?

2022-10-05 11:57 UTC, epereskokov requested changes

2022-10-05 11:57 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
>              NetworkNewsRepository.newInstance().loadNews(new NewsLoadingCallback() {
обращение к репозиторию должно быть в презентере. Фрагмент должен содержать только работу с визуальными элементами по командам с презентера. Данные презентер должен присылать в командах.

2022-10-05 11:57 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> -            recyclerView.setLayoutManager(new GridLayoutManager(view.getContext(), 2));
инициализировать ресайклер нужно один раз в метода onViewCreated, а данные обновлять отдельным методом, просто передавая новые в существующий адаптер.

2022-10-07 06:41 UTC, epereskokov requested changes

2022-10-07 06:41 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/NewsPresenter.java
> +        getViewState().showNews();
я уже писал в предыдущем комменте, что ресайклер нужно инициализировать в методе фрагмента onViewCreated, а ты сейчас для этого желаешь вот этот довольно бессмысленный вызов showNews() из презентера - его лучше убрать.

2022-10-07 06:41 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/NewsPresenter.java
> +    public void showNews() {
этот метод ничего не показывает, он только загружает - поэтому больше подойдет название loadNews

2022-10-08 18:19 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +                adapter = new NewsAdapter(getContext(), onItemClickListener);
зачем тут пересоздавать адаптер при каждом действии? Адаптер должен создаваться при создании фрагмента и жить пока фрагмент жив. Могут меняться только данные в нем при необходимости,

2022-10-08 18:19 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +                OnItemClickListener onItemClickListener = new OnItemClickListener() {
и почему в методе, который вызывается при рефреше листа, сетися клик листенер? Здесь только и должна быть что вызов функции презентера на перезагрузку данных.

2022-10-09 09:33 UTC, epereskokov approved these changes

2022-10-09 10:33 UTC, merged