review version
ampp8800/Hochu_pomoch pull request #14
Opened 2022-10-03 20:58 UTC by ampp8800

2022-10-04 20:09 UTC, EitherNor commented
Задание было интегрировать мокси в экран авторизации. Оставь и для профиля, но в этот же пр добавь и для авторизации тоже

2022-10-04 20:11 UTC, EitherNor requested changes
Задание не выполнено

2022-10-05 12:09 UTC, epereskokov requested changes

2022-10-05 12:09 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/ProfileFragment.java
>      private final ListItem userListItem = repository.getUserListItem();
обращение к репозиторию допустимо только в презентере, он уже готовые данные  должен передавать во вью-слой.

2022-10-05 12:09 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/ProfileFragment.java
>      private final ListItem userListItem = repository.getUserListItem();
это касается все строк выше.

2022-10-07 06:48 UTC, epereskokov requested changes

2022-10-07 06:48 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/AuthorizationPresenter.java
> +        super.onFirstViewAttach();
super тут не нужно вызвать - родительский метод пустой, так что смысла нету.

2022-10-07 06:48 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/mvp/ProfilePresenter.java
> +        getViewState().showProfile(userListItem, friends);
два одинаковых вызова, один явно лишний.

2022-10-07 06:48 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/AuthorizationActivity.java
> +    public void entry() {
entry-это существительное, а должен быть глагол, описывающий действие. startAuthorization например или что-то такое.

2022-10-07 06:48 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/ProfileFragment.java
> +    public void disconnect() {
тут что-то странное, ты оверрайдишь метод вью стейта, который не вызываешь из презентера. По-моему в клик листенере достаточно напрямую вызвать profilePresenter.disconnect(); и все, без всяких методов мокси-вью.

2022-10-08 18:14 UTC, epereskokov approved these changes

2022-10-08 20:06 UTC, merged