help window
ampp8800/Hochu_pomoch pull request #2
Opened 2022-03-25 16:32 UTC by ampp8800

2022-03-25 17:51 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/Help.java
> +public class Help {
название Help мало что говорит - это может быть как текст крика о помощи, так и какая-то команда. Рекомендую уточнить, например HelpListItem или HelpCategoryListItem

2022-03-25 17:51 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/MainActivity.java
> +    ArrayList<Help> helps = new ArrayList<Help>();
инкапсуляция - все что может быть private - должно быть private

2022-03-25 17:51 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/MainActivity.java
> +        helps.add(new Help("Дети", R.drawable.children));
бонусное задание - сделай так, чтобы по клику на элемент в ресайклере на экране появлялся toast с названием элемента (Дети, Взрослые и т.п.)

2022-03-25 17:51 UTC, epereskokov commented on app/src/main/res/layout/activity_help.xml
> +        style="@style/TextStyle5" />
Попробуй дать стилю внятное название, например TextStyleTitle/TextStyleSubTitle, самому потом будет проще ориентироваться.

2022-03-25 17:51 UTC, epereskokov commented on app/src/main/res/layout/activity_help.xml
> +        android:text="Выберите категорию помощи"
строковые ресурсы обычно кладутся в string.xml в ресурсах, а в верстке подставляются как @string/your_string_name, советую сразу так делать (чтобы привыкать к хорошему так сказать). Это делается затем, чтобы у одного и того же текста на разных языках были переводы - это достигается тем, что делается несколько файлов strings.xml  на разных языках и андроид сам выбирает нужный в зависимости от языка системы.

2022-03-25 18:02 UTC, EitherNor commented
![image](https://user-images.githubusercontent.com/19414663/160176593-fa85edb4-e111-498f-a470-af6fe8ac8cdf.png)
нижние надписи уехали чутка за экран в горизонтальной ориентации

2022-03-25 18:05 UTC, EitherNor requested changes

2022-03-25 18:05 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/Help.java
> +public class Help {
Что означает это название? Я не понимаю, речь о приложении? Какой-то призыв к помощи? 
Назови понятнее, я только по полям догадался, что это элемент твоего списка категорий помощи

2022-03-25 18:05 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/Help.java
> +    private String name; // название
Такие комменты действительно необходимы?

2022-03-25 18:05 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/Help.java
> +    private int imageHelpResource; // ресурс флага
Эти поля могут быть final

2022-03-25 18:05 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/Help.java
> +    public void setName(String name) {
Ты же всегда создаешь эти объекты через конструктор - точно нужны сеттеры этих полей?

2022-03-25 18:05 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/HelpAdapter.java
> +    private final List<Help> helps;
Название раковое опять же

2022-03-25 18:05 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/HelpAdapter.java
> +    public static class ViewHolder extends RecyclerView.ViewHolder {
Лучше, чтобы твои имена классов не были похожи на библиотечные, это будет сильно путать. Добавляй префиксы по смыслу класса

2022-03-25 18:05 UTC, EitherNor commented on app/src/main/res/layout/help_items.xml
> +<?xml version="1.0" encoding="utf-8"?>
Название в единственном числе, у тебя же элемент списка

2022-03-25 22:59 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/Help.java
> +public class Help {
Поменял

2022-03-25 23:00 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/MainActivity.java
> +    ArrayList<Help> helps = new ArrayList<Help>();
добавил префикс

2022-03-25 23:00 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/MainActivity.java
> +        helps.add(new Help("Дети", R.drawable.children));
добавил toast

2022-03-25 23:02 UTC, ampp8800 commented on app/src/main/res/layout/activity_help.xml
> +        style="@style/TextStyle5" />
тут не стал ничего менять, файл со стилями (themes.xml) приложен к ТЗ, название взято от туда, думаю в дальнейшем на него тоже будут ссылаться

2022-03-25 23:03 UTC, ampp8800 commented on app/src/main/res/layout/activity_help.xml
> +        android:text="Выберите категорию помощи"
поправил строковые ресурсы и назначение строк в текстовых вью

2022-03-25 23:04 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/Help.java
> +public class Help {
поменял название класса

2022-03-25 23:04 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/Help.java
> +    private String name; // название
убрал лишние комментарии

2022-03-25 23:04 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/Help.java
> +    private int imageHelpResource; // ресурс флага
добавил префикс final

2022-03-25 23:05 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/Help.java
> +    public void setName(String name) {
убрал сеттеры из класса

2022-03-25 23:05 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/HelpAdapter.java
> +    private final List<Help> helps;
поменял название класса

2022-03-25 23:05 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/HelpAdapter.java
> +    private final List<Help> helps;
поменял название переменной

2022-03-25 23:06 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/HelpAdapter.java
> +    public static class ViewHolder extends RecyclerView.ViewHolder {
поменял название класса

2022-03-25 23:06 UTC, ampp8800 commented on app/src/main/res/layout/help_items.xml
> +<?xml version="1.0" encoding="utf-8"?>
поменял название лейаута

2022-03-26 08:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/HelpAdapter.java
> +    private final List<HelpListItem> helpListItem;
у тебя название списка айтемов совпадает с названием айтема. А их у тебя много

2022-03-26 08:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/HelpAdapter.java
> +    public class HelpAdapterViewHolder extends RecyclerView.ViewHolder {
Смысла держать этот вьюхолдер внутри адаптера нет, особенно если и адаптер и вью холдер будут посложнее - лучше явно разносить по разным файлам эти классы

2022-03-26 14:16 UTC, merged

2022-03-26 14:25 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/HelpAdapter.java
> +    HelpAdapter(Context context, List<HelpListItem> helpListItems, OnHelpItemClicked onHelpItemClicked) {
Когда передаешь объекты куда-то, обозначай их аннотацией @Nullable/@NonNull, таким образом тебе ИДЕ будет потом подсвечивать места, в которых ты случайно попытаешься вызывать метод у объекта, который может быть null. Это превентивная защита от NPE.
Аннотацией могут помечаться как аргументы метода/конструктора, например:
```
HelpAdapter(@NonNull Context context, @NonNull List<HelpListItem> helpListItems, @NonNull OnHelpItemClicked onHelpItemClicked) {
...
}
```

так и методы - тогда аннтоация работает на возвращаемое из метода значение, например

```
@Nullable
public String getStatus() {
if (anyCondition) {
return "status"
} else {
return null
}
```

2022-03-26 14:25 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/OnHelpItemClicked.java
> +public interface OnHelpItemClicked {
Отлично, только опять будь чуть точнее с неймингом, у тебя класс должен быть существительным, в данном случае правильнее будет OnHelpItemClickListener.
Метод внтури интерфейса тоже можешь поближе к реальности назвать, например onHelpItemClick()