Profile edit
ampp8800/Hochu_pomoch pull request #3
Opened 2022-03-29 19:50 UTC by ampp8800

2022-03-30 08:07 UTC, EitherNor requested changes

2022-03-30 08:07 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +                .load("https://sun9-63.userapi.com/impf/c625318/v625318902/28050/-l1-yQ4qIQk.jpg?size=1365x2048&quality=96&sign=4a8023e5f2a744ec6004f35725341e88&type=album.png")
Вынеси ссылку в константу

2022-03-30 08:07 UTC, EitherNor commented on app/src/main/res/layout/friend_item.xml
> +        android:id="@+id/name_friend"
tv_something

2022-03-30 08:07 UTC, EitherNor commented on app/src/main/res/layout/friend_item.xml
> +        android:id="@+id/image_friend"
iv_something

2022-03-30 08:07 UTC, EitherNor commented on app/src/main/res/layout/toolbar_profile.xml
> +<?xml version="1.0" encoding="utf-8"?>
Если у тебя тулбары на разных экранах отличаются не сильно, можно использовать один и тот же ресурс, просто переключая видимость разных иконок, например

2022-03-30 08:07 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/MainActivity.java
> +        //переделать это говно
Ты верно заметил - можно вынести инициализацию тулбара в общее для всех экранов место, чтобы не плодить копипасту

2022-03-30 09:07 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +        recyclerView.setLayoutManager(new GridLayoutManager(getApplicationContext(), 1));
если список без колонок - лучше использовать LinearLayoutManager

2022-03-30 09:07 UTC, epereskokov commented on app/src/main/res/layout/activity_profile.xml
> +                android:text="Константинов Денис"
данные профиля лучше инициализировать не статично, а сделать какой-то источник данных, чтобы сэмулировать реальное поведение. В реальности ты же информацию о профиле грузишь из сети. Пока с сетью не работаешь - сделай класс ProfileRepository и оттуда получай всю личную информацию для этого экрана.

2022-03-30 09:08 UTC, epereskokov commented
Прикладывай скриншоты того как получилось плс.

2022-03-30 09:13 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +                .load("https://sun9-63.userapi.com/impf/c625318/v625318902/28050/-l1-yQ4qIQk.jpg?size=1365x2048&quality=96&sign=4a8023e5f2a744ec6004f35725341e88&type=album.png")
тут лучше получать всю инфу о профиле извне (например как я написал в другом комменте - из отдельного класса репозитория), чтобы эмулировать реальные процессы загрузки инфы из сети например.

2022-03-30 10:04 UTC, EitherNor commented
У тебя по системной кнопке назад кидает по истории переходов между экранами. Сделай логику такую, что есть главный экран - MainActivity, если мы с другого экрана жмем назад - попадаем на главный, а с главного на рабочий стол

2022-04-06 23:21 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +                .load("https://sun9-63.userapi.com/impf/c625318/v625318902/28050/-l1-yQ4qIQk.jpg?size=1365x2048&quality=96&sign=4a8023e5f2a744ec6004f35725341e88&type=album.png")
сделал класс ProfileRepository с ссылками на данные профиля

2022-04-06 23:21 UTC, ampp8800 commented on app/src/main/res/layout/friend_item.xml
> +        android:id="@+id/name_friend"
поправил

2022-04-06 23:22 UTC, ampp8800 commented on app/src/main/res/layout/friend_item.xml
> +        android:id="@+id/image_friend"
поправил

2022-04-06 23:22 UTC, ampp8800 commented on app/src/main/res/layout/toolbar_profile.xml
> +<?xml version="1.0" encoding="utf-8"?>
объединил тулбары

2022-04-06 23:22 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/MainActivity.java
> +        //переделать это говно
переработал нижний тулбар

2022-04-06 23:23 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +        recyclerView.setLayoutManager(new GridLayoutManager(getApplicationContext(), 1));
поменял layout manager

2022-04-06 23:23 UTC, ampp8800 commented on app/src/main/res/layout/activity_profile.xml
> +                android:text="Константинов Денис"
сделал класс ProfileRepository с ссылками на данные профиля

2022-04-07 07:26 UTC, EitherNor requested changes

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/BottomNavigationLogic.java
> +    public void switchingSectionsByAccrual() {
Что мешает на каждую кнопку сделать свой листенер вместо этой конструкции с перебором id? Получится меньше кода и читать легче будет

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/BottomNavigationLogic.java
> +    View newsButton;
private final? И ниже. Интент на уровне класса не нужен, если ты его используешь только в одном методе

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/BottomNavigationLogic.java
> +    public BottomNavigationLogic(Context context, View view) {
`@NonNull` на аргументы не забывай ставить или соответственно `@Nullable` если ты ожидаешь нулла

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/FriendAdapter.java
> +    private View view;
Это лишнее

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/FriendAdapter.java
> +        holder.imageFriendView.setImageResource(targetImageViewFromUrl(friend.getImageViewURL()));
Эта логика должна быть во вью холдере. Адаптер только для управления списком айтемов, их внутреннюю логику сами вью холдеры реализуют

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/FriendAdapter.java
> +    private int targetImageViewFromUrl(String imageViewURL) {
Нон-нулл аргумент

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/MainActivity.java
> +        BottomNavigationLogic bottomNavigationLogic = new BottomNavigationLogic(this, (View) findViewById(R.id.bottom_navigation));
Раньше ты любил везде пихать статику, а теперь, когда она нужна - не используешь почему-то)

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +    private ArrayList<ProfileRepository.FriendListItem> friends = (ArrayList<ProfileRepository.FriendListItem>) ProfileRepository.getProfileRepository().getFrendsList();
Что за касты (ArrayList<ProfileRepository.FriendListItem>)? У тебя тип переменной и так должен соответствовать типу данных в репозитории

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +    private void setImageViewFromInternet(Context context, int idImageView, String imageViewURL) {
Nullable / NonNulll аргументы

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileItem.java
> +    public ProfileItem(String name, ImageView imageView, List<FriendListItem> list) {
Nullable / NonNulll аргументы

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileItem.java
> +    public ImageView getIvProfile() {
геттеры и сеттеры должны быть ниже конструкторов в классе, так принято в конвенции по джава коду

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileItem.java
> +    private ImageView ivProfile;
final?

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileItem.java
> +        public FriendListItem(String name, ImageView imageView) {
Nullable / NonNulll аргументы

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileItem.java
> +        private ImageView imageView;
final

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileItem.java
> +    public class FriendListItem {
Избавляйся от привычки делать внутренние классы. Никакого профита в этом нет, только раздувает файл и все в одной куче получается, сложнее читать. Если ты имел в виду, что у тебя и инфа о профиле и о друзьях принадлежит одному экрану - сделай пакет например data/profile/ и положи туда 2 отдельных класса с этими данными

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileRepository.java
> +    public static ProfileRepository getProfileRepository() {
когда реализуют паттерн синглтон, такие методы называют getInstance()

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileRepository.java
> +    public static ProfileRepository getProfileRepository() {
Опять же `@NonNull` над методом, чтобы обозначить что ты не вернешь отсюда нулл

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileRepository.java
> +    private static String imageViewURL;
Зачем здесь эти поля, если у тебя есть класс ProfileItem?

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileRepository.java
> +            imageViewURL = "https://sun9-63.userapi.com/impf/c625318/v625318902/28050/-l1-yQ4qIQk.jpg?size=1365x2048&quality=96&sign=4a8023e5f2a744ec6004f35725341e88&type=album.png";
Всю статичную инфу в константы

2022-04-07 07:26 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileRepository.java
> +    public static class FriendListItem {
Какое-то дублирование классов, рядом есть такие же, но не статические. Надо убрать лишнее

2022-04-07 18:23 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/BottomNavigationLogic.java
> +public class BottomNavigationLogic extends AppCompatActivity {
Это наследник activity,  в названии тоже должно быть слово активити (BottomNavigationActivity).

2022-04-07 18:23 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/BottomNavigationLogic.java
> +public class BottomNavigationLogic extends AppCompatActivity {
Вообще я не понял, зачем тут наследоваться от активити. Если наследуешься - значит либо делай эту активити абстрактной и наследуйся от нее в тех активити, где есть нижнее меню и вызывай метод инициализации тулбара, либо убирай наследование и переименовывай в какой-нибудь ToolbarController и используй так, как используешь сейчас.

2022-04-07 18:23 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/MainActivity.java
> +        Intent startMain = new Intent(Intent.ACTION_MAIN);
не понял, что ты тут хочешь открыть - из mainActivity открыть mainActivity?

2022-04-07 18:23 UTC, epereskokov commented on app/src/main/res/layout/friend_item.xml
> +        android:src="@drawable/avatar_frend"
старайся указывать app:srcCompat вместо android:src, потому что на старых андроидах не было поддержки векторной графики и если ты передать ссылку на вектор просто через src, то во время работы на старом андроиде приложение у тебя упадет.

2022-04-07 18:23 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileRepository.java
> +    public static class FriendListItem {
Видимо Леща хотел сделать отдельный класс для профиля и отдельный класс для друзей. Я бы тоже посоветовал не делать отдельные классы, а использовать один общий, пускай даже для друзей там будет немного избыточная информация.

2022-04-10 14:50 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/MainActivity.java
> +        Intent startMain = new Intent(Intent.ACTION_MAIN);
эта строка нужна, чтобы разворачивая экран открывался сразу MainActivity, а не SplashActivity

2022-04-11 11:42 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/FriendListItemViewHolder.java
> +    public static int targetImageViewFromUrl(@NonNull String imageViewURL, @NonNull Context context) {
почему static?

2022-04-11 11:42 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/FriendListItemViewHolder.java
> +    public static int targetImageViewFromUrl(@NonNull String imageViewURL, @NonNull Context context) {
обычно делают метод 
```
bind(@NonNull FriendItem item) 
```
и просто вызывают его, а внутри 
```
holder.bind(item)
```
уже пишут всю логику по инициализации вью-холдера информацией из айтема.

2022-04-11 11:42 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/BottomNavigationLogic.java
> +    public static void switchingSectionsByAccrual(@NonNull Context context, @NonNull View view) {
название метода странное, что тут в реальности происходит? По-моему инициализация нижней панели, следует это и отразить в названии.

2022-04-11 11:42 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/MainActivity.java
> +        helps.add(new ListItem((String) getText(R.string.children), R.drawable.children));
перенеси данные в репозиторий и оттуда доставай.

2022-04-11 11:42 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/MainActivity.java
> +        Intent startMain = new Intent(Intent.ACTION_MAIN);
не понял до конца - здесь переопределяется onBackPressed, то есть нажимая "назад" сейчас запускается mainActivity. Какую проблему ты тут решаешь? Когда выходишь из приложения кнопкой "назад", то при переоткрытии не показываешь сплеш? Так он должен показываться, если приложение закрывалось.

2022-04-11 11:42 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +        textView.setText(ProfileRepository.getInstance().getNameProfile());
ProfileRepository.getInstance() дублируется много раз. принцип DRY нарушается.
```
ProfileRepository repository = ProfileRepository.getInstance();  
```
в переменную класса.

2022-04-11 11:42 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +        setImageViewFromInternet(context, R.id.iv_profile, ProfileRepository.getImageViewUrl());
лучше в репозитории не хранить отдельные поля, а хранить целый объект с информацией о профиле и его здесь использовать. Я бы предложил либо создать отдельный класс Profile либо расширить ListItem нужными полями (и обозвать его чуть подробнее, например UserListItem)

2022-04-11 11:42 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +                .with(context)
пока картинка не подгрузилась, обычно отображают какой-то статичный плейсхолдер. Здесь в билдере его можно указать, вроде через .placeholder. Выбери в интернете подходящий и добавь в ресурсы ну и дай сюда ссылку на него.

2022-04-11 11:42 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +        Intent intent = new Intent(ProfileActivity.this, MainActivity.class);
а почему здесь не закрываешь текущую активити через finish()?

2022-04-15 11:10 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/MainActivity.java
> +        helps.add(new ListItem((String) getText(R.string.children), R.drawable.children));
это системные данные приложения, все равно переносить в репозиторий?

2022-04-15 12:00 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/MainActivity.java
> +        Intent startMain = new Intent(Intent.ACTION_MAIN);
так до конца не разобрался как это все работает в интенте, в общем если 1 из этих (70-73) строк отсутствует, то при нажатии кнопки назад начинают возникать ошибки. Переделал метод к следующему виду

@Override
public void onBackPressed() {
        this.moveTaskToBack(true);
}

внешне выполняют ту же функцию, но теперь mainActivity может быть выгружено из памяти системой (опять же если я все понял из описания)

2022-04-15 13:22 UTC, EitherNor requested changes

2022-04-15 13:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/FriendListItemViewHolder.java
> +    public void bind(List<ListItem> friendListItems, int position, Context context) {
Что мешает передать сюда только нужные тебе параметры, то есть имя и урл? Зачем вью холдеру одного друга инфа о всех параметрах вообще всех друзей?

2022-04-15 13:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ListItem.java
> +    public ListItem(String name, String imageViewURL, String dateOfBirth, String fieldOfActivity) {
@NonNull

2022-04-15 13:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ListItem.java
> +    public String getDateOfBirth() {
@NonNull и с другими методами то же самое

2022-04-15 13:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +    private ProfileRepository repository = ProfileRepository.getInstance();
final и ниже тоже

2022-04-15 17:06 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/BottomNavigationLogic.java
> +    public static void bottomBarInitialization(@NonNull Context context, @NonNull View view) {
метод должен иметь в названии глагол, метод же делает действие - вот это и надо в названии отражать. (что делаю? Инициализирую епта)
initializeBottomBar()

2022-04-15 17:06 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/FriendListItemViewHolder.java
> +    public int targetImageViewFromUrl(@NonNull String imageViewURL, @NonNull Context context) {
context можно из View получить, не обязательно его передавать в параметрах.

2022-04-15 17:06 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileRepository.java
>      public static String getDateOfBirth() {
отдавай отсюда сразу getCurentUser() вместо набора специализированных методов, их можно будет вызвать уже в месте получения по необходимости.

2022-04-17 18:58 UTC, EitherNor requested changes

2022-04-17 18:58 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/FriendAdapter.java
> +    public void onBindViewHolder(@NonNull FriendListItemViewHolder holder, @NonNull int position) {
@NonNull int position 
зачем тут @NonNull ?

2022-04-17 18:58 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/FriendListItemViewHolder.java
> +    public int targetImageViewFromUrl(@NonNull String imageViewURL) {
Этот метод точно должен быть public?

2022-04-17 18:58 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/FriendListItemViewHolder.java
> +    public int targetImageViewFromUrl(@NonNull String imageViewURL) {
И название у него всратое, сделай отражающим суть (загрузка картинки)

2022-04-17 18:58 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/FriendListItemViewHolder.java
>          return R.drawable.ic_no_photo;
Это разве не должен быть плейсхолдер?

2022-04-17 18:58 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/HelpAdapter.java
> +    public HelpListItemViewHolder onCreateViewHolder(@NonNull ViewGroup parent, @NonNull int viewType) {
Убирай нон-нуллы с примитивов, мы для чего обсуждали сегодня этот вопрос?

2022-04-17 18:58 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ListItem.java
> +    @NonNull
удоли

2022-04-17 18:58 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +    private Context context;
почему эти 2 поля не final?

2022-04-17 18:58 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileRepository.java
>      public static String getDateOfBirth() {
Неиспользуемые методы надо удалить

2022-04-17 18:58 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileRepository.java
> +    public static ListItem getUserListItem() {
Почему здесь статик, если ты все равно работаешь с репозиторием через getInstance? И нон-нулла нет

2022-04-17 19:20 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/FriendListItemViewHolder.java
>          return R.drawable.ic_no_photo;
я больше скажу, ничего не нужно возвращать из метода, дефолтная картинка должна ставится методами самого глайда
```
 Glide
                .with(view.getContext())
                .load(imageViewURL)
                .placeholder(R.drawable.ic_no_photo)
                .into((ImageView) view.findViewById(R.id.civ_friend));
```
или как-то так, от версии к версии глайда там название метода может отличаться.
Но за хитрое решение тебе плюс.:)

2022-04-17 19:20 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/FriendListItemViewHolder.java
>          return R.drawable.ic_no_photo;
бтв ты в ProfileActivity же нормально сделал, почему ту по-другому?

2022-04-18 08:08 UTC, EitherNor approved these changes

2022-04-18 08:09 UTC, merged