Authorization screen
ampp8800/Hochu_pomoch pull request #4
Opened 2022-04-14 14:23 UTC by ampp8800

![Screenshot_2022-04-14-17-18-57-316_com ampp8800 hochupomoch](https://user-images.githubusercontent.com/87927435/163410790-ecab7e20-d38a-4fd5-ad81-c2514786f931.jpg)
![Screenshot_2022-04-14-17-19-44-615_com ampp8800 hochupomoch](https://user-images.githubusercontent.com/87927435/163410792-18f988f9-3d41-4548-9421-7405564e871d.jpg)

2022-04-14 14:43 UTC, epereskokov requested changes

2022-04-14 14:43 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/AuthorizationActivity.java
> +    public void login(View view) {
этот метод не вызывается нигде - ты забыл добавить клик листенер?

2022-04-14 14:43 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/AuthorizationActivity.java
> +        ProfileRepository.setAuthorization(((EditText) findViewById(R.id.et_edit_e_mail)).getText().toString(), ((EditText) findViewById(R.id.et_edit_password)).getText().toString());
в onCreate сохрани ссылки на вьюхи в переменные класса, а здесь только получай из них значения.

2022-04-14 14:43 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileRepository.java
> +    public static void setAuthorization(String login, String password) {
репозиторий - это исключительно источник данных. Логику авторизации (в твоем случае сверка данных) сейчас лучше перенести в отдельный метод активити. 
В целом это считается "бизнес-логикой" и выносится в отдельный слой между активити и репозиторием, но сейчас это не требуется.

2022-04-14 14:43 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileRepository.java
> +        if (login.equals(LOGIN) && password.equals(PASSWORD)) {
предлагаю в качестве факультативного упражнения номер раз чуть усложнить логику - если не совпадает логин - на ui выводить ошибку "пользователь не найден", если совпадает логин, но не совпадает пароль - выводить "неверный пароль".

2022-04-14 14:43 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +        ProfileRepository.setAuthorization("","");
лучше сделать отдельный метод  clearAuthData(), который внутри уже будет занулять значения. Иначе плохая читаемость - ты вдруг записываешь пустые авторизационные данные, это не слишком очевидная операция тут.

2022-04-14 14:43 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileRepository.java
> +    public static boolean getAuthorization(Context context) {
сделай отдельный репозиторий для авторизации. Репозитории - это специализированные хранилища, все в кучу валить - потом сам запутаешься что где.

2022-04-14 14:43 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/AuthorizationActivity.java
> +        registration.setOnClickListener(clickedView -> startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("http://www.apple.com"))));
избегай повторяющегося кода, если видишь такой - выноси одинаковый код в отдельный метод. В данном случае это openUrl(@NonNull Uri url)

2022-04-14 14:43 UTC, epereskokov commented on app/src/main/res/layout/activity_authorization.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Еще одно доп. упражнение - в горизонтальной ориентации контент должен занимать 70% от ширины экрана по центру. В этом тебе поможет ConstraintLayout и GuideLine (свойство layout_constraintGuide_percent)

2022-04-14 14:48 UTC, EitherNor commented
Расстояние от иконок соцсетей до надписи "Или авторизуйтесь через приложение" меньше, чем в макете. 

Положения глаза перепутано - когда он перечеркнут, пароль не должно быть видно. Глаз отражает состояние инпута в данный момент. 

В неактивном состоянии у инпута нижняя полоска сливается с фоном
Вводимый текст неверного цвета и обрезается сверху - admin буква d обрезана и тд

В горизонтальной ориентации кнопки ссылок плотную к нижнему краю экрана, надо бы добавить отступ

2022-04-14 14:59 UTC, EitherNor requested changes

2022-04-14 14:59 UTC, EitherNor commented on app/src/main/res/layout/activity_authorization.xml
> +                android:onClick="login"
Всю подобную логику лучше делать в java коде, где и читать удобнее и отлаживать. Если тебе для того чтобы понять что делает кнопка обязательно надо идти в верстку - это лишняя трата времени

2022-04-14 14:59 UTC, EitherNor commented on app/src/main/res/layout/activity_profile.xml
> +                    android:onClick="logout"
См. коммент про логин

2022-04-22 12:48 UTC, epereskokov requested changes

2022-04-22 12:48 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/AuthorizationActivity.java
> +            ((Guideline) findViewById(R.id.guide_left)).setGuidelinePercent(0.15f);
Так (программно) тоже можно, но нежелательно. Такие вещи делаются статичной версткой для разных конфигураций экрана.
https://developer.android.com/guide/topics/resources/providing-resources
В твоем случае нужно разместить одноименный альтернативный лейаут в папке layout-land, он автоматически подхватиться в альбомной ориентации. (не забудь, что полностью весь лейаут копировать не нужно, достаточно добавить туда только отличающуюся часть)
В будущем можно делать более изощренные конструкции - например layout-w600dp-land - лейатуы из этой папки будут браться только тогда, когда у тебя альбомная ориентация и ширина экрана не меньше 600 дп. Все возможные модификаторы описаны в статье по ссылке.

2022-04-22 12:48 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/AuthorizationRepository.java
> +    public static void setAuthorization(boolean value) {
static нинужна. Название я бы чуть поменял на setAuthorized

2022-04-22 12:48 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/AuthorizationRepository.java
> +    public static boolean getAuthorization(Context context) {
isAuthorized логичнее.
Принято, что геттеры, возвращающие boolean, начинаются с is (isAuthorized, isDeepDarkFantasies etc.)

2022-04-24 21:06 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/AuthorizationRepository.java
> +    public static void setAuthorization(boolean value) {
![image](https://user-images.githubusercontent.com/87927435/164996511-ce27032b-cf8e-4094-9857-4f1dbe58e82a.png)
тут этот метод используется без экземпляра класса, если нужно - добавлю, но не уверен

2022-04-25 09:09 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/AuthorizationRepository.java
> +    public static void setAuthorization(boolean value) {
используй с экземпляром класса.:)
И с именами ты запутался, ты поменял setAuthorization на isAuthorized, а нужно было на setAuthorized

2022-04-25 09:14 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/AuthorizationActivity.java
> +            ((Guideline) findViewById(R.id.guide_left)).setGuidelinePercent(0.15f);
Кстати есть еще вариант проще - внутри xml в значение подставить
layout_constraintGuide_percent="@dimen/side_guide_value", а значение side_guide_value задать разными в файлах dimens в папках values и values-land. 
Для values-land : <dimen name="side_guide_value">0.15<dimen>
Для values: <dimen name="side_guide_value">0.0<dimen>

2022-04-25 10:38 UTC, epereskokov commented on app/build.gradle
> +    sourceSets {
и без этого будет работать автоматически.

2022-04-25 10:38 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/AuthorizationRepository.java
> +    public  boolean isAuthorization(Context context) {
isAuthorized

2022-04-25 10:38 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ProfileActivity.java
> +                AuthorizationRepository.getInstance().setAuthorized(false);
в переменные класса сразу вынеси репозиторий.

2022-04-25 13:31 UTC, epereskokov approved these changes

2022-04-25 13:32 UTC, merged