Search screen
ampp8800/Hochu_pomoch pull request #5
Opened 2022-05-18 17:24 UTC by ampp8800

2022-05-18 17:38 UTC, EitherNor commented
1. Почему на двух вкладках по-разному работает поиск? На второй работает нормально, на первой не ищет
2. После поворота экрана поиск и состояние списков сбрасывается, так не должно быть
3. После поиска внизу какая-то лишняя серая полоска на последнем элементе, проверь

2022-05-18 17:42 UTC, EitherNor commented
![image](https://user-images.githubusercontent.com/19414663/169107622-1e9df02f-2270-4c0e-9f75-5b9d646f20b0.png)
Описывай в каждом коммите краткую суть, над чем работал, что сделал. Такие сообщения к коммитам не прокатят на работе, где больше одного человека в команде

2022-05-18 17:50 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/SearchActivity.java
> +        // инициализация тулбара
вот вместо комментов просто сделай метод initToolbar() и перенеси в него строчки под комментом. Это же касается и остальных комментариев ниже. Вообще принцип простой - если хочется написать коммент - просто выдели кусок кода с комментов в отдельный метод с понятным названием.

2022-05-18 17:50 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/EventsRepository.java
> +    private static void newEventsList() {
а почему бы не делать это в конструкторе сразу?

2022-05-18 17:50 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +    private String extractionOfKeywords(String keywords) {
в названии метода должен быть глагол. Extraction - это существительное. extractKeywords будет верным названием.
Тоже самое с wordComparison

2022-05-18 17:51 UTC, epereskokov commented
скриншоты плс (желательно планшетную версию тоже, можно только ее)

2022-05-18 18:22 UTC, EitherNor requested changes
Нужно прикрепить скриншоты всех основных состояний - данные не фильтрованы, данные фильтрованы, в разных ориентациях экрана

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/EventItem.java
> +    public EventItem(String organization, String name) {
`@NonNull String organization` и тд

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/EventItem.java
> +    private String organization;
final и в других таких же полях

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/EventsRepository.java
> +    private static void newEventsList() {
Здесь ты не создаешь список, а заполняешь его. Вот и назови метод более подобающе

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchAdapter.java
> +    public void updatePageAttachment(String searchQery, @NonNull int currentItem) {
Название не понятное, с аннотацией @NN к аргументам перепутал местами

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchAdapter.java
> +        ((SearchPageFragment) fragmentActivity.getSupportFragmentManager().findFragmentByTag("f" + currentItem))
А зачем здесь ссылка на активити? Ты же этот метод из активити и так вызываешь, кек

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchAdapter.java
> +    private FragmentActivity fragmentActivity;
ссылка нинужна, читай коммент к методу updatePageAttachment

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchListAdapter.java
> +    private final OnItemClickListener onSearchItemClickListner;
Никто не просил делать здесь этот листенер, задания такого не было

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchListAdapter.java
> +        String search = searchListItems.get(position);
Не осилил логику этих 2 строк, пояснишь?

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +    private ArrayList<String> searches = new ArrayList<>();
Очень плохое название, я не понимаю что за переменная, почему она должна здесь быть

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +            pageNumber = 1;
Зачем эта ветка, если ты всегда создаешь фрагмент одинаковым образом с аргументами?

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +        context = result.getContext();
нет надобности сохранять контекст в активити и фрагментах, он всегда доступен встроенным методом от супера getContext()

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +    private ArrayList<String> searches = new ArrayList<>();
Посмотрев ниже, кажется это дублирование данных в адаптере. Не надо так делать, все данные списка должны быть в адаптере и изменять их надо тоже в нем же

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +    public void setDataInFragmentBody() {
Здесь просто данные из репозитория надо сетить в адаптер, дополнительно хранить их копию во фрагменте не нужно и вредно. Объекты вью (активити, фрагменты) не должны хранить никаких данных, т.к. их жизненным циклом управляет система, они должны отвечать только за интерфейс

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +    public int setDataInFragmentBody(@NonNull String searchQuery, @NonNull int currentItem) {
Можно уже начинать выносить логику из вью классов. В этом задании логику поиска лучше поместить в репозиторий, чтобы имитировать например запросы к базе данных или к серверу. То есть твое взаимодействие должно быть таким - получить из репозитория весь набор данных или получить из репозитория данные, отфильтрованные по ключевым словам.

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +    private boolean wordComparison(@NonNull String desired, @NonNull String original) {
Перемудрил жестко ты с логикой поиска. Наверное поэтому и работает плохо. В помощь метод класса String **contains**, весь поиск делается в 2 цикла - по исходным данным репозитория и по твоим ключевым словам

2022-05-18 18:22 UTC, EitherNor commented on app/src/main/res/layout/activity_search.xml
> +        android:id="@+id/tab_search"
tab - это таба, одна. У тебя же TabLayout

2022-05-18 18:53 UTC, ampp8800 commented
![image](https://user-images.githubusercontent.com/87927435/169127403-025e9ac4-75aa-436c-97cc-c61c19cd9410.png)
![image](https://user-images.githubusercontent.com/87927435/169127713-a3c696ca-5044-4c03-a414-87b8bc37f3a3.png)
![image](https://user-images.githubusercontent.com/87927435/169128700-af38552c-e935-49be-be7c-26de0c62ced4.png)
Прикрепил скриншоты

2022-05-18 19:05 UTC, ampp8800 commented
![image](https://user-images.githubusercontent.com/87927435/169136081-de1e2702-feed-4f4a-8841-8387320bb412.png)
![image](https://user-images.githubusercontent.com/87927435/169136306-d5f060b4-9f87-48eb-986e-c21abde557ea.png)
Скриншоты с планшета

2022-05-31 17:09 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/SearchListAdapter.java
> +        String search = searchListItems.get(position);
Заполняет RecyclerView данными из searchListItems

2022-06-05 09:55 UTC, EitherNor requested changes

2022-06-05 09:55 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/EventsRepository.java
> +        if (searchQuery.equals("")) {
У строк есть встроенный метод проверки на пустоту String.isEmpty()

2022-06-05 09:55 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/EventsRepository.java
> +                String event;
Название не отражает сути. Сюда ты записываешь поле, по которому ищешь, назови переменную соответствующе

2022-06-05 09:55 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/EventsRepository.java
> +                } else {
А если у тебя потом станет не 2 вкладки, а 3, к примеру добавится новое поле в ивенте? Лучше обрабатывай такие моменты явно, чтобы потом приходилось искать почему что-то не работает. Если ты предусматриваешь только 2 вкладки, для остальных значений можешь напечатать в консоль предупреждение, что значение некорректно и выбросить исключение IllegalArgument, например

2022-06-05 09:55 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchListAdapter.java
> +        if (pageNumber == 0) {
То же самое, обрабатывай явно 0 и 1 позиции

2022-06-05 09:55 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +                searchQery = savedInstanceState.getString("eventsList0", "");
eventsList0 - что за название аргумента? Называй по смыслу поиска, eventListByName например и тд и вынеси в константу эту строку

2022-06-05 09:55 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +                searchQery = savedInstanceState.getString("eventsList1", "");
А зачем тебе 2 разных аргумента? У каждого экземпляра фрагмента свой бандл и свое значение будет записано, они не будут путаться между собой. Достаточно одного аргумента

2022-06-05 09:55 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +                searchQery = savedInstanceState.getString("eventsList0", "");
Назови переменную более понятно, без этих цифр в конце

2022-06-05 09:55 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +                searchQery = savedInstanceState.getString("eventsList1", "");
Зачем 2 разных аргумента? У каждого экземпляра фрагмента свой бандл и они не будут путаться между собой, достаточно одного

2022-06-05 09:55 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +                        savedInstanceState.getString("searchingResult1", ""));
Здесь у тебя выше уже есть эта строка, а ты еще раз лезешь за ней в бандл

2022-06-05 09:55 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +                insertSearchDescription(savedInstanceState.getString("keywords1", ""),
С ключевыми словами то же самое, достаточно одного аргумента

2022-06-05 09:55 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/SearchPageFragment.java
> +        if (pageNumber == 0) {
Здесь тоже ни к чему разделять это

2022-06-05 11:51 UTC, epereskokov commented
![Screenshot_1654429780](https://user-images.githubusercontent.com/25001737/172049099-23ba59b2-697e-43f7-a655-e5ea0856ae7a.png)
фотка в профиле куском видна, явно у ImageView надо сделать другой scaleType

2022-06-05 11:55 UTC, epereskokov commented
Бонусное задание - автоматический поиск. Через 2 секунды после ввода искать автоматически при условии, что запрос в поле поменялся. Пустую строку игнорировать офк.

2022-06-05 11:58 UTC, epereskokov commented
Бонусное задание №2 - переделать все вкладки на фрагменты - у тебя должна получится 1 базовая активити с минимумом логики и все остальные экраны - это фрагменты. Навигацию по экранам советую вынести в отдельный класс AppRouter или AppNavigator, как тебе больше нравится. Предлагаю это сделать отдельным пулл-реквестом после всех остальных правок.

2022-06-05 12:09 UTC, epereskokov commented
FriendListItemViewHolder убери плс модификатор статик из этого класса из поля view

2022-06-05 12:11 UTC, epereskokov commented
пора немного структурировать классы, так как их становится все больше. Пока предлагаю базово структуру из 2 папок - это ui и data.  В data понятное дело надо положить все репозитории, так это и есть источники данных и модели (dto), которые ты в этих репозиториях используешь, в ui - все остальное.

2022-06-05 12:14 UTC, epereskokov requested changes

2022-06-05 12:14 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/EventsRepository.java
> +                    if (event.toLowerCase().contains(queryWord.toLowerCase())) {
есть метод equalsIgnoreCase, из названия я думаю понятно, как он сравнивает.:)

2022-06-05 12:14 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/AuthorizationActivity.java
> +        findViewById(R.id.search_layout).setVisibility(View.GONE);
у тебя это поле нужно только в 1 месте, скрой его по-умолчанию, чтобы везде руками не скрывать.

2022-06-05 12:14 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/EventsRepository.java
> +                } else {
согласен. И поэтому лучше передавать не pageNumber, а создать енам SearchType и его передавать в качестве параметра в метод.

2022-06-05 12:14 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/EventsRepository.java
> +                } else {
и в SearchPageFragment.getInstance тоже его передавать. Привыкай там, где есть неизменяемые типы данных, использовать не ничего не говорящие константы (int, строки), а енамы с говорящими названиями, так ты здорово поможешь себе в будущем, когда нужно будет добавлять новый функционал.

2022-06-05 12:15 UTC, epereskokov commented
в нижней напели всегда выбрана вкладка "новости", а должна быть выбрана та, которая сейчас видна пользователю.

![Screenshot_1654431265](https://user-images.githubusercontent.com/25001737/172049935-b43f775a-b2c6-425e-94e3-5b917f25b382.png)

2022-06-10 18:53 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/EventsRepository.java
> +                } else {
попробовал _SearchPageFragment.newInstance(int);_ представить как _SearchPageFragment.newInstance(SearchType);_
но теряется смысл, т.к. я использую абстрактный метод _createFragment(int);_, мне нужно в нем условно переводить int в _SearchType_, а потом в _SearchPageFragment_ переводить _SearchType_ в _int_  для хранения в _Bundle_

2022-06-10 23:26 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/EventsRepository.java
> +                    if (event.toLowerCase().contains(queryWord.toLowerCase())) {
тут или так, или как изначально сделал

[EitherNor](https://github.com/EitherNor) [23 days ago](https://github.com/ampp8800/Hochu_pomoch/pull/5#discussion_r876207163)
Перемудрил жестко ты с логикой поиска. Наверное поэтому и работает плохо. В помощь метод класса String contains, весь поиск делается в 2 цикла - по исходным данным репозитория и по твоим ключевым словам

2022-06-10 23:41 UTC, ampp8800 commented
поправил скейлинг изображения в _ProfileActivity_ через _dimen_, использовал рекомендованные множители, годится такое решение задачи?

2022-06-11 08:51 UTC, EitherNor requested changes

2022-06-11 08:51 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/EventsRepository.java
> +    public static List<EventItem> getListOfEvents(@NonNull String searchQuery, SearchType currentSearchType) {
@NonNull  SearchType currentSearchType

2022-06-11 08:51 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/EventsRepository.java
>                  } else {
Почему не добавил явную обработку второго типа поиска-то?

2022-06-11 08:51 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchActivity.java
> +                if (!((EditText) findViewById(R.id.et_search_query)).getText().toString().equals("")){
Проверка на пустую строку String.isEmpty()

2022-06-11 08:51 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchActivity.java
> +        new Handler().postDelayed(new Runnable() {
Логика неправильная. Ты ищешь через 2 секунды после открытия экрана, а в задании сказано "после ввода", т.е. надо искать, когда пользователь ввел поисковую строку и ничего не делает в течение 2 секунд

2022-06-11 09:48 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/EventsRepository.java
> +                } else {
В Bundle можно передавать Serializable. Чтобы сделать енам Serializable, просто сделай extends Serializable у него. Ну а когда из бандла достаешь - просто сделай каст в нужный тип енама (SearchType) bundle.getSerializable(ARGUMENT_NAME)

2022-06-11 09:58 UTC, epereskokov requested changes

2022-06-11 09:58 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchActivity.java
> +        new Handler().postDelayed(new Runnable() {
подсказка - у текст вью есть листенер на ввод (TextWatcher вроде)

2022-06-11 09:58 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/data/SearchType.java
> +public enum SearchType {
у тебя этот енам используется только во фрагментах (то есть на UI) - тогда и перенеси его в соответствующую папку.

2022-06-11 09:58 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/data/EventsRepository.java
>  import java.util.List;
я тебе писал, что тут надо заполнять в конструкторе. Ты перенес в newInstance() заполнение данными почему-то. А конструктор по-прежнему пустой.

Еще и events почему-то стало статическим.

 private EventsRepository() {
//заполнять данными тут
    }

2022-06-14 09:09 UTC, EitherNor requested changes

2022-06-14 09:09 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchActivity.java
> +                new Handler().postDelayed(new Runnable() {
Тебе нужно отслеживать здесь, не печатает ли пользователь в эти 2 секунды. Если печатает - нужно сбрасывать и заново запускать таймер

2022-06-14 09:09 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchActivity.java
> +        ((EditText) findViewById(R.id.et_search_query)).addTextChangedListener(new TextWatcher() {
Вынеси это в отдельный метод

2022-06-14 20:03 UTC, EitherNor requested changes

2022-06-14 20:03 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchActivity.java
> +    private void autoSearch(EditText editText) {
`@NonNull EditText editText`

2022-06-14 20:03 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchActivity.java
> +    private void autoSearch(EditText editText) {
И в название метода тогда уж добавь init в начале

2022-06-16 05:59 UTC, epereskokov requested changes

2022-06-16 05:59 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchPageFragment.java
> +        switch (getArguments().getInt("num")) {
вместо int клади и доставай Serializable как я писал в другом комменте

2022-06-16 05:59 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchPageFragment.java
> +        switch (getArguments().getInt("num")) {
https://github.com/ampp8800/Hochu_pomoch/pull/5#discussion_r895003026

2022-06-16 06:05 UTC, epereskokov commented
https://github.com/ampp8800/Hochu_pomoch/pull/5#issuecomment-1152803000

не годится. Вот как у тебя сейчас выглядит на планшете.

![Screenshot_1655359392](https://user-images.githubusercontent.com/25001737/174002374-b629842b-8479-4a1e-a369-58aaf36de617.png)

Я выше скинул скрин как должно быть + подсказал, что надо использовать другой scaleType у ImageView. Все решается одной строчкой.

2022-06-16 18:09 UTC, epereskokov approved these changes

2022-06-16 18:46 UTC, EitherNor approved these changes

2022-06-16 18:46 UTC, merged