Transition to fragments
ampp8800/Hochu_pomoch pull request #6
Opened 2022-07-03 14:17 UTC by ampp8800

2022-07-03 15:24 UTC, EitherNor requested changes

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomMenuButton.java
> +    HISTORU_BUTTON,
History

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +    private Fragment helpFragment = HelpFragment.newInstance();
Новые инстансы надо создавать при навигации, а не при создании этого класса

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +        if (!searchFragment.isInLayout()) {
Проверять надо в методе обработки нажатия, достаточно 1 раз проверять есть ли на экране текущий фрагмент

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +    public BottomNavigationLogic(FragmentActivity fragmentActivity, @NonNull View view) {
@NN FragmentActivity fragmentActivity

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +    private BottomMenuButton buttonWasPreviouslyPress;
Поле не должно принимать значения Null, т.к какой-то экран всегда выбран. Название лучше поменять на что-то типа "нажатая кнопка" или "выбранная кнопка"

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +    public BottomMenuButton getEnumOfPressedButton() {
@NonNull над методом

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +    public void startSearchFragment() {
Обобщить вместо 3 копипастных методов сделать 1 универсальный "показать фрагмент" с параметрами

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +    private void selectButtonSearch() {
То же самое, вынести логику в 1 метод

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +        if (buttonWasPreviouslyPress != null) {
Когда уберешь состояние нулл, проверка станет не нужна

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +                case SEARCH_BUTTON:
Добавить в енам поля с ид кнопки и выбранного / невыбранного состояний, потом получать здесь гетерами без свича

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +    public void showPreviousApp(BottomMenuButton buttonWasPreviouslyPress) {
Название непонятное, поменять

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/HelpFragment.java
> +    private ArrayList<ListItem> helps = new ArrayList<ListItem>();
final

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/HelpFragment.java
> +    private ArrayList<ListItem> helps = new ArrayList<ListItem>();
+ название сделать более понятным

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/HelpFragment.java
> +    public static HelpFragment newInstance() {
@NonNull над методом

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/HelpFragment.java
> +        OnItemClickListener onItemClickListener = new OnItemClickListener() {
Вынеси все что с комментариями в отдельные методы

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/MainActivity.java
> +    private final String PRESS_BUTTON = "pressButton";
1. Название некорректное, должно быть что-то типа "нажатая кнпока". 
2. К названиям аргументов всегда добавляем в начале ARG_

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/MainActivity.java
> +        if (bottomNavigationLogic.getEnumOfPressedButton() != BottomMenuButton.HELP_BUTTON) {
==

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/ProfileFragment.java
> +public class ProfileFragment extends Fragment {
AppCompatFragment, проверь в остальных тоже

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/ProfileFragment.java
> +    public static ProfileFragment newInstance() {
`@NonNull`

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchFragment.java
> +    Handler handler = new Handler();
private final?

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchFragment.java
> +    public static SearchFragment newInstance() {
`@NonNull`

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchFragment.java
> +    private void setUpAppBar(ActionBar actionBar) {
@NonNull

2022-07-03 15:24 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchFragment.java
> +        getActivity().findViewById(R.id.iv_icon_back).setVisibility(View.GONE);
requireActivity() вместо getActivity, если не обрабатываешь что там может быть нулл

2022-07-04 21:06 UTC, epereskokov requested changes

2022-07-04 21:06 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomMenuButton.java
> +    public void setSelect(boolean select) {
ты нигде вроде эти поля не используешь, убери их.

2022-07-04 21:06 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +    public BottomMenuButton getEnumOfPressedButton() {
getPressedButton просто, что возвращаемый тип тут енам - не играет роли и не дает никакой информации.

2022-07-04 21:06 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +        if () {
пустой иф

2022-07-04 21:06 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/MainActivity.java
> +            bottomNavigationLogic.showPreviousApp((BottomMenuButton) savedInstanceState.getSerializable(PRESS_BUTTON));
фрагмент менеджер сохраняет внутри себя состояние фрагментов при повороте, тебе не нужно самому тут восстанавливать состояние.
Более того - фрагмент менеджер может хранить так называемый backstack - это очередь показанных фрагментов (историю по сути), по которой ты можешь ходить (например вызывая fragmentManager.popBackStack() ты возвращаешься на предыдущий фрагмент, открытый до этого). Единственный момент - чтобы экран попал в бекстек, ты должен его туда положить, добавив в транзакцию перехода на фрагмент .addToBackStack. Сейчас тебе история не нужна, но в будущем может понадобиться.

2022-07-04 21:06 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchFragment.java
> +        ((EditText) getActivity().findViewById(R.id.et_search_query)).setOnEditorActionListener(new TextView.OnEditorActionListener() {
view.findViewById? и ниже тоже, зачем getActivity

2022-07-04 21:06 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/HelpFragment.java
> +            helps.add(new ListItem((String) getText(R.string.children), R.drawable.children));
повторяющийся код. Один из принципов разработк - DRY, Don't Repeat Yourself.
Если ты видишь повторяющийся код - выноси в отдельный метод и вызывай его.
Например тут 
void addHelpItem(@StrinRes int text, @DrawableRes int icon) {
helps.add(new ListItem((String) getText(text), icon));
}

2022-07-06 14:40 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/ui/MainActivity.java
> +            bottomNavigationLogic.showPreviousApp((BottomMenuButton) savedInstanceState.getSerializable(PRESS_BUTTON));
этот метод не создает новых фрагментов, он используется только для перекрашивания кнопки на нижней панели

2022-07-06 14:45 UTC, ampp8800 commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchFragment.java
> +        ((EditText) getActivity().findViewById(R.id.et_search_query)).setOnEditorActionListener(new TextView.OnEditorActionListener() {
если меняю на view ловлю _Process: com.ampp8800.hochupomoch, PID: 20725
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setOnEditorActionListener(android.widget.TextView$OnEditorActionListener)' on a null object reference_

2022-07-06 15:52 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/MainActivity.java
> +            bottomNavigationLogic.showPreviousApp((BottomMenuButton) savedInstanceState.getSerializable(PRESS_BUTTON));
да, в глаза долблюсь. Ну может хоть справку про фрагмент менеджер не зря написал.:)

2022-07-06 16:01 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/SearchFragment.java
> +        ((EditText) getActivity().findViewById(R.id.et_search_query)).setOnEditorActionListener(new TextView.OnEditorActionListener() {
findViewById и прямое использование вьюхи должно быть в том классе фрамгента/активити, где она расположена. 
У тебя тулбар расположен в активити в данном случае получается. Оставляй так тогда, пофиг, дольше переделывать.:)

2022-07-06 20:23 UTC, EitherNor requested changes

2022-07-06 20:23 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomMenuButton.java
> +    //    NEWS_BUTTON("newsButton", R.color.leaf, R.color.warm_grey, iconSelect, iconUnselect, button, title),
Закомменченный код надо удалять

2022-07-06 20:23 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomMenuButton.java
> +    private final int colorSelect;
textColorSelected

2022-07-06 20:23 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomMenuButton.java
> +    private final int colorUnselect;
textColorUnselected

2022-07-06 20:23 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomMenuButton.java
> +    private final int iconSelect;
Аналогично selected, unselected. Чекай правильный перевод слова "выбранный"

2022-07-06 20:23 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomMenuButton.java
> +    private final int colorSelect;
Нужны аннотации @ColorRes, @DrawableRes и тд

2022-07-06 20:23 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomMenuButton.java
> +    public int getColorSelect() {
Над геттерами так же нужны аннотации типа возвращаемого инта

2022-07-06 20:23 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +        startFragment(ProfileFragment.newInstance(), BottomMenuButton.PROFILE_BUTTON);
Можно прямо так по месту вызова и писать вместо этих startProfileFragment и тд, у тебя содержимое метода это 1 строка. Избавься от этих методов

2022-07-06 20:23 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +    private void startFragment(@NonNull Fragment newFragment, BottomMenuButton newPressedButton) {
`@NonNull newPressedButton` ?

2022-07-06 20:23 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/BottomNavigationLogic.java
> +    private void recolorButton(@DrawableRes int drawbleNewImage, @ColorInt int color) {
repaintButton - перекрасить кнопку

2022-07-06 20:23 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/HelpFragment.java
> +    private void addCategoriesItem(@StringRes int text, @DrawableRes int icon) {
Та же ситуация - ни к чему 1 строку прятать в метод, получаешь на выходе то же самое + код самого метода

2022-07-06 20:23 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/HelpFragment.java
> +    private void setCategoryList(@NonNull View view, @NonNull Context context) {
Метод делает куда больше того, что написано в названии, не кажется?)

2022-07-06 20:23 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/HelpFragment.java
> +    private void setCategoryList(@NonNull View view, @NonNull Context context) {
Больше похоже на инициализацию списка твоего

2022-07-07 07:41 UTC, EitherNor approved these changes

2022-07-07 07:43 UTC, merged