News fragment
ampp8800/Hochu_pomoch pull request #7
Opened 2022-07-10 16:41 UTC by ampp8800

2022-07-10 16:52 UTC, EitherNor requested changes

2022-07-10 16:52 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsItem.java
> +    public NewsItem(int photoNews, @NonNull String newsHeadline, @NonNull String briefDescriptionOfNews, @NonNull String date) {
@DrawableRes int photoNews

2022-07-10 16:52 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsItem.java
> +    public int getPhotoNews() {
@DrawableRes

2022-07-10 16:52 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsItem.java
> +public class NewsItem {
@NonNull забыл на геттерах

2022-07-10 16:52 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsAdapter.java
> +        holder.photoNews.setImageResource(news.getPhotoNews());
Унести в метод bind внутри вьюхолдера

2022-07-10 16:52 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsAdapter.java
> +        final ImageView photoNews;
Эти поля  private

2022-07-10 16:52 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +    private final ArrayList<NewsItem> news = new ArrayList<>();
Унести данные в репозиторий

2022-07-10 17:31 UTC, EitherNor commented
Следующее задание
Изучить работу с сетью
Использовать библиотеку **Retrofit2**
Нужно сделать источник сетевых данных, который будет получать данные с сервера. Модель данных составить из полей, полученных в ответе сервера. 
Для сетевых и БД вызовов нужно использовать фоновые потоки, т.к. это тяжелые операции. Для выполнения сетевого вызова в фоновом потоке использовать класс **AsyncTask**.

2022-07-11 19:51 UTC, epereskokov requested changes

2022-07-11 19:51 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +    private void initializeListOfCategories(@NonNull View view, @NonNull Context context) {
тут явно не категории.

2022-07-11 19:51 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +        recyclerView.setHasFixedSize(true);
не факт что тут фиксированное количество, новостей может быть разное количество в будущем.

2022-07-11 19:51 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +            recyclerView.setLayoutManager(new GridLayoutManager(view.getContext(), 2));
новости в 2 колонки? Вроде там всегда в одну, я правда не помню уже дизайн.:)

2022-07-11 19:51 UTC, epereskokov commented on app/src/main/res/layout/news_item.xml
> +            android:maxLines="2"
с maxLines  используется еще свойство ellipsize, которое указывает что делать, если текст не помещается (start/center/end вроде) - заменит автоматом заменит троеточием часть контента в указаной части.

2022-07-11 19:51 UTC, epereskokov commented on app/src/main/res/layout/news_item.xml
> +        <androidx.constraintlayout.widget.ConstraintLayout
constraintLayout в constraintLayout мы не вкладываем, все можно в рамках корневого разрулить. Констрейнт для того и сделан, чтобы можно было избегать вложенности. Если будут сложности - пиши мне или Диме.

2022-07-12 13:49 UTC, epereskokov approved these changes

2022-07-12 19:25 UTC, EitherNor approved these changes

2022-07-12 19:25 UTC, merged