Getting data from server
ampp8800/Hochu_pomoch pull request #8
Opened 2022-07-22 13:04 UTC by ampp8800

2022-07-22 13:31 UTC, EitherNor requested changes

2022-07-22 13:31 UTC, EitherNor commented on app/build.gradle
> +    implementation 'com.squareup.retrofit2:converter-scalars:2.3.0'
когда добавляешь несколько библиотек, связанных с одной и той же технологией, разделяй строки пробелами чтобы группировать их визуально и подписывай коммент сверху типа //retrofit

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/api/MessagesApi.java
> +    Call<List<NewsModel>> messages();
 Это явно гет метод, название должно быть как у геттера

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/api/MessagesApi.java
> +public interface MessagesApi {
Явно не так должно называться, ты же новости получаешь

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/api/NewsModel.java
> +public class NewsModel {
По всему классу не хватает нон-нуллов или нуллабл

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsItem.java
> +    private String getMonth(DateTime dateTime) {
Есть встроенные методы для этого, поищи. Мало того, что это кринж, так еще и только для одного языка работает

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +    private NewsRepository newsRepository;
Аннотации над полями

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +    private NewsRepository newsRepository;
Это поле лучше назвать instance, иначе непонятно, зачем оно нужно

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +    private class DateLoader extends AsyncTask<Void, Void, ArrayList<NewsItem>> {
Название таски должно отражать, что это экземпляр AsyncTask. И у тебя он загружает не просто Data какую-то, а конкретно NewsItem - новости. Вот и назови соответственно

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +    private class DateLoader extends AsyncTask<Void, Void, ArrayList<NewsItem>> {
Геттер тоже

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +        dateLoader.execute();
Так get или execute? Определись

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +    public static NewsRepository newInstance(View view, NewsAdapter adapter) {
Репозиторий не должен знать ни о каких вьюхах. Он у тебя здесь хранит вечно ссылку на вью, мешая жизненному циклу вью андроида и создавая риск утечек памяти

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +    public static NewsRepository newInstance(View view, NewsAdapter adapter) {
Все операции с вью можно сделать коллбеками, которые ты можешь передавать в репозиторий в методе для создания и выполнения таски

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +        protected void onPreExecute() {
Принимай в конструктор твоей таски 2 коллбека - для onPreExecute и для onPostExecute - так ты вынесешь работу с вью из репозитория, но оставишь работу с асинк таской в нём

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +    public static NewsRepository newInstance(View view, NewsAdapter adapter) {
Ни вью ни адаптера в репозитории быть не должно. Нарушается цепочка зависимостей. Репозиторий не должен зависеть от твоих вью и адаптеров. Это они зависят от него

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsAdapter.java
> +    public void updateNewsListItems(@NonNull List<NewsItem> newsListItems) {
что мешает здесь и вызвать notifyDatasetChanged? никто кроме адаптера не должен выполнять этот метод

2022-07-22 13:31 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +    private NewsRepository newsRepository;
Создавай инстанс прямо здесь, иначе у тебя аннотация не соответствует реальности

2022-07-23 12:00 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/api/NewsModel.java
> +    public void setGuid(String guid) {
сеттеры не нужны, ты же эту модель с сервера получаешь, сетить что-то сюда ты вряд ли будешь. Можно их убрать.

2022-07-25 15:37 UTC, EitherNor requested changes

2022-07-25 15:37 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/api/newsInformation.java
> +public interface newsInformation {
Интерфейсы и классы всегда с большой буквы, согласно Java Code Conventions

2022-07-25 15:37 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +    private static class NewsItemsLoader extends AsyncTask<Void, Void, ArrayList<NewsItem>> {
NewsItemsLoaderAsyncTask

2022-07-25 15:37 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsScreenUpdater.java
> +    void newsScreenUpdate(List<NewsItem> newsListItems);
@NonNull List<NewsItem> newsListItems

2022-07-25 15:37 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +            newsScreenUpdater.newsScreenUpdate(news);
Здесь даже не обязательно 2 метода уже, раз ты изначально решил по-умолчанию показывать прогрессар. Просто скрывай его внутри реализации этого метода

2022-07-25 15:37 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +                adapter.updateNewsListItems(newsListItems);
Вот здесь прям и скрывай свой прогрессбар, второй метод не нужен

2022-07-25 15:39 UTC, epereskokov requested changes

2022-07-25 15:39 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsScreenUpdater.java
> +public interface NewsScreenUpdater {
Докопаюсь по неймингу. Во-первых - ты названием загрузку новостей жестко привязываешь к конкретному экрану. А завтра тебе надо в другом месте подгрузить эти новости - сразу получается фигня, на каком-нибудь GachiScreen почему-то вызывается newsScreenUpdate(). 
Надо в названии отражать суть самой операции а не место, где она будет применена. Здесь суть - что новости загрузились, ты хочешь об этом просигнализировать. Вот и назови NewsLoadingCallback.
Ну и 2 метода лишние, по-моему можно оставить только первый (его тоже нужно переименовать по сути, догадайся как из предложенного названия класса).

2022-07-26 11:50 UTC, EitherNor approved these changes

2022-07-26 11:51 UTC, merged