Adding room library
ampp8800/Hochu_pomoch pull request #9
Opened 2022-08-16 14:40 UTC by ampp8800

2022-08-16 14:51 UTC, EitherNor requested changes

2022-08-16 14:51 UTC, EitherNor commented on app/src/main/AndroidManifest.xml
> +        android:name=".db.HochuPomochApplication"
Зачем это?

2022-08-16 14:51 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +                if (isConnect) {
Это уже не работа с данными, а бизнес-логика. Её не нужно держать в репозитории. Разруливай это уровнем выше

2022-08-16 14:51 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +                        newsEntity.setGuid(item.getGuid());
Такие вещи выноси в метод с названием типа newsItemToNewsEntity(NewsItem newsItem) - получается метод-конвертер

2022-08-16 14:51 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/db/HochuPomochApplication.java
> +public class HochuPomochApplication extends Application {
Этот класс должен быть в корне или в пакете app, но никак не в пакете db

2022-08-16 14:51 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/db/HochuPomochApplication.java
> +public class HochuPomochApplication extends Application {
По методам не забывай развешивать нуллабл и нон-нуллы

2022-08-16 14:51 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/db/NewsEntity.java
> +    public void setGuid(String guid) {
параметр нн

2022-08-16 14:51 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +        newsRepository = NewsRepository.newInstance(networkInfo != null && networkInfo.isConnected());
Тебе нужно разрулить источник данных здесь. Сделай второй репозиторий, один у тебя будет для данных из сети, второй для данных из бд и определяй, что вызывать и откуда брать данные

2022-08-16 14:51 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +        newsRepository = NewsRepository.newInstance(networkInfo != null && networkInfo.isConnected());
Ну и назвать репозитории надо будет соответственно, сейчас у тебя наследие со времен, когда источник был один и это название уже не актуально

2022-08-16 16:07 UTC, epereskokov requested changes

2022-08-16 16:07 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +    public static NewsRepository newInstance(boolean isConnect) {
Интернет - штука переменчивая, сейчас нет - через 10 секунд есть. Так что передавать его в виде константного значения сюда некорректно. Как следствие - бонусное задание тебе сразу - добавить в ресайклер pull-to-refresh (когда тянешь вниз в начале списка - и он перезагружается). По названию найдешь примеры.

2022-08-16 16:07 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepository.java
> +    public static NewsRepository newInstance(boolean isConnect) {
Интернет - вещь непостоянная, передавать его в качестве константы в параметре - некорректно.

В качестве бонусного задания тебе нужно в списке новостей сделать pull-to-refresh, чтобы по соответствующему жесту перезагружать список новостей.

2022-08-17 13:16 UTC, ampp8800 commented on app/src/main/AndroidManifest.xml
> +        android:name=".db.HochuPomochApplication"
создав подкласс Application необходимо указывать его полное имя в качестве атрибута "android:name" в теге <application> файла AndroidManifest.xml. Подкласс класса Application создается перед любым другим классом при создании процесса для приложения

2022-08-17 15:52 UTC, epereskokov requested changes

2022-08-17 15:52 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/data/InternalNewsRepository.java
> +    private static final ArrayList<NewsItem> news = new ArrayList<>();
а зачем эта переменная? Новости грузятся при каждом обращении же, тут нечего хранить.

2022-08-17 15:52 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepositoryFromNetwork.java
> +    private static final ArrayList<NewsItem> news = new ArrayList<>();
тут я тоже не понял, зачем эта переменная.

2022-08-17 15:52 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepositoryFromNetwork.java
> +                    IOException e) {
форматирование уехало

2022-08-17 15:52 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/data/InternalNewsRepository.java
> +    public void executeNewsLoadingAsyncTask(@NonNull NewsLoadingCallback newsLoadingCallback) {
AsyncTask - это подробность внутренней реализации, она ничего не говорит о сути метода. Когда я хочу загрузить новости - я хочу увидеть метод loadNews(..), а как уж он там внутри реализован - мне по барабану. Название должно отражать суть того, что метод делает, а не КАК он это делает.
Тожн самое и для второго репозитория.

2022-08-18 14:53 UTC, EitherNor requested changes

2022-08-18 14:53 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/HochuPomochApplication.java
> +package com.ampp8800.hochupomoch.ui;
Либо в пакет app либо в корень

2022-08-18 14:53 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/InternalNewsRepository.java
> +    public void NewsLoadingAsyncTask(@NonNull NewsLoadingCallback newsLoadingCallback) {
1. Метод назван с большой буквы
2. Название метода не должно содержать подробностей реализации, текущее название один хрен неправильное с точки зрения нейминга

2022-08-18 14:53 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/InternalNewsRepository.java
> +public class InternalNewsRepository {
Что значит Internal? Это может быть файл на диске, просто какой-то кэш, а у тебя это база. Вот и назови понятным образом

2022-08-18 14:53 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/InternalNewsRepository.java
> +        protected void onPreExecute() {
Этот метод ничего не переопределеяет же - можно его не указывать?

2022-08-18 14:53 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepositoryFromNetwork.java
> +public class NewsRepositoryFromNetwork {
Слово From не несет в данном случае никакого особого смысла, остальных слов хватит чтобы понять суть. Только учись правильно их компоновать, чтобы начав читать первым делом видеть отличающие похожие классы слова и лишь потом - общие. В данном случае NetworkNewsRepository

2022-08-18 14:53 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepositoryFromNetwork.java
> +    public void NewsLoadingAsyncTask(@NonNull NewsLoadingCallback newsLoadingCallback) {
та же фигня с названием что и в другом репозитории

2022-08-18 14:53 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepositoryFromNetwork.java
> +                    .baseUrl("https://eithernor.github.io/help-server/")
строку бейс урл в константу

2022-08-18 14:53 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepositoryFromNetwork.java
> +        public void newsItemToNewsEntity(@NonNull NewsEntityDao newsEntityDao,
что здесь делает дао?

2022-08-18 14:53 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NewsRepositoryFromNetwork.java
> +        public void newsItemToNewsEntity(@NonNull NewsEntityDao newsEntityDao,
Этот метод должен конвертировать одно в другое и все. Дао пример результат конвертации уровнем выше, не надо его никуда прокидывать

2022-08-18 14:53 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +    private void refreshNewsListOnScreen(@NonNull NewsAdapter adapter, @NonNull View view, @NonNull List newsListItems) {
Адаптер тоже не надо никуда прокидывать. Пусть сидит в переменной класса. Он один и не меняется

2022-08-18 14:53 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +    private void refreshNewsListOnScreen(@NonNull NewsAdapter adapter, @NonNull View view, @NonNull List newsListItems) {
Вью тоже не нужна в параметрах - во фрагменте её всегда можно взять у супера

2022-08-18 14:53 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +
удоли

2022-08-19 10:30 UTC, epereskokov requested changes

2022-08-19 10:30 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/data/InternalNewsRepository.java
> +    public void NewsLoadingAsyncTask(@NonNull NewsLoadingCallback newsLoadingCallback) {
Сегодня асинкТаск - завтра гачиТаск, послезавтра ХуйнянеймТаск, разве эта информация важна тому, кто будет вызвать этот метод?

2022-08-19 10:30 UTC, epereskokov commented on app/src/main/java/com/ampp8800/hochupomoch/ui/NewsFragment.java
> +                swipeRefreshLayout.setRefreshing(false);
а почему сразу выключаешь анимацию рефреша? Она должна выключаться тогда, когда ты получил данные. А получаешь ты их в другом методе этого класса. Либо здесь опционально можно показать прогресс-бар, который у тебя уже есть вместо анимации этого лейаута.
Сейчас у тебя получается, что ты еще на загрузил даннеы - а анимацию прогресса уже не показываешь, нехорошо. Для тестов можешь в асинкТаску в doOnBackground вставить задержку Thread.sleep(2000), чтобы новости грузились подольше.

2022-08-19 11:38 UTC, EitherNor requested changes

2022-08-19 11:38 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NetworkNewsRepository.java
> +    public void newsLoading(@NonNull NewsLoadingCallback newsLoadingCallback) {
спроси у тани, как перевести "загрузить новости", если не получается самому

2022-08-19 11:38 UTC, EitherNor commented on app/src/main/java/com/ampp8800/hochupomoch/data/NetworkNewsRepository.java
> +    private final static String baseUrl = "https://eithernor.github.io/help-server/";
константы всегда называем ВОТ_ТАК

2022-08-19 11:54 UTC, epereskokov approved these changes

2022-08-19 12:11 UTC, merged